// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/avobl/sample-gqlgen/internal/model"
)

type Mutation struct {
}

type NewUser struct {
	Type *model.UserType `json:"type,omitempty"`
}

type Query struct {
}

type User struct {
	Type *model.UserType `json:"type,omitempty"`
}
